version: '3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - backend
  mysql:
    image: percona/percona-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pressmogul
      MYSQL_DATABASE: pressmogul
      MYSQL_USER: pressmogul
      MYSQL_PASSWORD: pressmogul
    volumes:
      - database:/var/lib/mysql
    networks:
      - backend
  wordpress:
    image: pressmogul/wordpress:nightly
    environment:
      WP_DB_HOST: mysql
      WP_DB_USER: pressmogul
      WP_DB_PASSWORD: pressmogul
      WP_DB_NAME: pressmogul
      WP_DB_PORT: '3306'
      WP_TABLE_PREFIX: dc
    depends_on:
      - mysql
    volumes:
      - content:/var/www/wordpress/wp-content
    networks:
      - backend
    ports:
      - 80:80
networks:
  backend:
volumes:
  database:
  content:
