version: '2'
services:
  mysql:
    image: percona/percona-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    mem_limit: 256m
    mem_reservation: 128m
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  wordpress:
    image: dockium/wordpress:4.9.1_1
    environment:
      WP_DB_HOST: mysql
      WP_DB_USER: wordpress
      WP_DB_PASSWORD: wordpress
      WP_DB_NAME: wordpress
      WP_DB_PORT: '3306'
      WP_TABLE_PREFIX: zp
    depends_on:
      - mysql
    mem_limit: 256m
    mem_reservation: 128m
    volumes:
      - app:/var/www/
    networks:
      - frontend
      - backend
  nginx:
    image: nginx:1.13-alpine
    depends_on:
      - wordpress
    mem_limit: 32m
    mem_reservation: 16m
    ports:
      - 80:80
      - 443:443
    volumes:
      - app:/var/www/
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
networks:
  frontend:
  backend:
volumes:
  db:
  app:
