version: '3'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
  mysql:
    image: percona/percona-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: docked
      MYSQL_DATABASE: docked
      MYSQL_USER: docked
      MYSQL_PASSWORD: docked
    volumes:
      - database:/var/lib/mysql
    networks:
      - backend
  wordpress:
    image: docked/wordpress:5.0.3
    environment:
      WP_DB_HOST: mysql
      WP_DB_USER: docked
      WP_DB_PASSWORD: docked
      WP_DB_NAME: docked
      WP_DB_PORT: '3306'
      WP_TABLE_PREFIX: dd
      WP_ENV: 'development'
      WP_DEBUG: 'true'
      WP_DEBUG_LOG: 'false'
      WP_DEBUG_DISPLAY: 'true'
      SCRIPT_DEBUG: 'false'
      HOST_GID: '1000'
      HOST_UID: '1000'
      WP_INSTALL: 'true'
      WP_SITE_URL: localhost
      WP_SITE_TITLE: Docked
      WP_ADMIN_USER: docked
      WP_ADMIN_PASSWRD: docked
      WP_ADMIN_EMAIL: docked@pressmogul.com
    depends_on:
      - mysql
    volumes:
      - ./content:/var/www/wordpress/wp-content
    networks:
      - backend
    ports:
      - 80:80
networks:
  backend:
volumes:
  database:
